defaults:
  - _self_

name: visual_world_model
type: visual
latent_channels: 64
hidden_channels: 512
action_embedding_dim: 8
context_length: 3
pred_length: 5
observation_dt: ${dataset.dt}
encoder_frames: 2
