defaults:
  - _self_

name: visual_world_model
type: visual
latent_channels: 64
hidden_channels: 512
beta: 0.003
free_bits: 0.0
fixed_logvar: false
action_embedding_dim: 8
context_length: 3
pred_length: 5
predictor_weight: 1.0
latent_pred_weight: 0.01
velocity_weight: 0.0
observation_dt: ${dataset.dt}
encoder_frames: 2
