_target_: src.models.predictors.HamiltonianPredictor
name: hamiltonian
latent_dim: ${model.latent_channels}
action_dim: ${env.action_dim}
action_embedding_dim: ${model.action_embedding_dim}
hidden_dim: 256
dt: ${dataset.dt}
n_steps: 1
integration_method: euler
damping_init: -1.0
