_target_: src.models.predictors.LatentNeuralODEPredictor
name: latent_neural_ode
latent_dim: ${model.latent_channels}
action_dim: ${env.action_dim}
action_embedding_dim: ${model.action_embedding_dim}
hidden_dim: 256
gru_hidden: 128
theta_dim: 8
dt: ${dataset.dt}
