_target_: src.models.predictors.NewtonianPredictor
name: newtonian
latent_dim: ${model.latent_channels}
action_dim: ${env.action_dim}
action_embedding_dim: ${model.action_embedding_dim}
hidden_dim: 256
dt: ${dataset.dt}
integration_method: rk4
damping_init: -1.0
